url: http://gkaczorek.com
title: Somewhat disjointed
description: Almost personal development blog by Greg Kaczorek
author: Greg Kaczorek
date_format: "%b %-d, %Y"

future: true
plugins: [jekyll-paginate]

# Google services
google_analytics:
google_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: GregPK
bitbucket_username: GregPK
stackoverflow_id:
twitter_username: gregpk
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: true


# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", 'smart', 'tables',]
permalink:    pretty
paginate:     10
sass:
  compressed: true
